EOS-11753_build_ha:  Improve ha script to run repitatively
- Improved HW/IEM resource
- Imporoved SSPL resource
- Improved CSM resource
- Improved UDS resource

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

diff --git a/conf/script/build-cortx-ha b/conf/script/build-cortx-ha
--- a/conf/script/build-cortx-ha
+++ b/conf/script/build-cortx-ha
@@ -2,16 +2,64 @@
 
 set -eu -o pipefail
 
-HA_PATH="<HA_PATH>"
+PROG=$(basename $0)
+LOG_PATH="/var/log/seagate/cortx/ha"
+TMP_LOG="/tmp/ha.log"
+LOG="${LOG_PATH}/${0##*/}.log"
+
+resources=(
+    io_path_health-c1
+    io_path_health-c2
+    mgmt_path_health-c1
+    sspl_master_hw
+    node_iem_s3
+)
+
+dependency_resource=(
+    consul-c1
+    consul-c2
+    sspl-master
+    ldap-clone
+)
+
+handle_error() {
+    MSG=$(cat ${TMP_LOG})
+    echo "$(date '+%Y-%m-%d %H:%M:%S'): ${MSG}" >> ${LOG}
+    echo ${MSG} | grep -q "already" || {
+        echo "ERROR: ${MSG}"
+        exit 1
+    }
+}
+
+verify_resources() {
+    RESOURCE_LIST=$(pcs resource)
+    for resource in ${resources[@]}; do
+        echo ${RESOURCE_LIST} | grep -q ${resource} || {
+            echo "Error: ${resource} resource is missing. Log at ${LOG}"
+            exit 1
+        }
+    done
+    echo "HW and IEM resource configured successfully."
+}
+
+verify_dependency_resources() {
+    RESOURCE_LIST=$(pcs resource)
+    for resource in ${dependency_resource[@]}; do
+        echo ${RESOURCE_LIST} | grep -q ${resource} || {
+            echo "Error: ${resource} resource is missing. Log at ${LOG}"
+            exit 1
+        }
+    done
+    echo "Dependency resource check passed..."
+}
 
 init() {
-    # Get node name
-    node_list=$(salt-call --local pillar.get cluster:node_list --output=json)
-    host1=$(echo $node_list | jq '.["local"][0]' | sed s/\"//g)
-    host2=$(echo $node_list | jq '.["local"][1]' | sed s/\"//g)
+    # Check dependency resource
+    verify_dependency_resources
 
+    RESOURCE_LIST=$(pcs resource)
     # Restart csm to enable decision maker changes
-    pcs resource restart csm-agent
+    echo $RESOURCE_LIST | grep -q csm-agent && pcs resource restart csm-agent
 
     pcs cluster cib hw_cfg
     # Hardware io stack resource
@@ -19,35 +67,37 @@ init() {
         path='io' filename='io_path_health-c1' \
         op start timeout=30s interval=0s \
         op monitor timeout=30s interval=30s \
-        op stop timeout=30s interval=0s
+        op stop timeout=30s interval=0s 2> "${TMP_LOG}" || handle_error
+
     pcs -f hw_cfg resource create io_path_health-c2 ocf:seagate:hw_comp_ra \
         path='io' filename='io_path_health-c2' \
         op start timeout=30s interval=0s \
         op monitor timeout=30s interval=30s \
-        op stop timeout=30s interval=0s
+        op stop timeout=30s interval=0s 2> "${TMP_LOG}" || handle_error
+
     pcs -f hw_cfg resource create mgmt_path_health-c1 ocf:seagate:hw_comp_ra \
         path='mgmt' filename='mgmt_path_health-c1' \
         op start timeout=30s interval=0s \
         op monitor timeout=30s interval=30s \
-        op stop timeout=30s interval=0s
+        op stop timeout=30s interval=0s 2> "${TMP_LOG}" || handle_error
 
-    pcs -f hw_cfg resource group add c1 io_path_health-c1
-    pcs -f hw_cfg resource group add c2 io_path_health-c2
-    pcs -f hw_cfg resource group add csm-kibana mgmt_path_health-c1
-    pcs -f hw_cfg constraint order consul-c1 then io_path_health-c1
-    pcs -f hw_cfg constraint order consul-c2 then io_path_health-c2
-    pcs -f hw_cfg constraint order consul-c1 then mgmt_path_health-c1
+    pcs -f hw_cfg resource group add c1 io_path_health-c1 2> "${TMP_LOG}" || handle_error
+    pcs -f hw_cfg resource group add c2 io_path_health-c2 2> "${TMP_LOG}" || handle_error
+    pcs -f hw_cfg resource group add csm-kibana mgmt_path_health-c1 2> "${TMP_LOG}" || handle_error
+    pcs -f hw_cfg constraint order consul-c1 then io_path_health-c1 2> "${TMP_LOG}" || handle_error
+    pcs -f hw_cfg constraint order consul-c2 then io_path_health-c2 2> "${TMP_LOG}" || handle_error
+    pcs -f hw_cfg constraint order consul-c1 then mgmt_path_health-c1 2> "${TMP_LOG}" || handle_error
 
     # Hardware resource monitor by sspl master
     pcs -f hw_cfg resource create sspl_master_hw ocf:seagate:hw_comp_ra \
         path='storage_encl' filename='sspl_master_hw' \
         op start timeout=30s interval=0s \
         op monitor timeout=30s interval=30s \
-        op stop timeout=30s interval=0s
-    pcs -f hw_cfg resource update sspl_master_hw meta migration-threshold=1 failure-timeout=40s
-    pcs -f hw_cfg constraint colocation add sspl_master_hw with sspl-master INFINITY with-rsc-role=Master
-    pcs -f hw_cfg constraint location sspl_master_hw prefers $host1=INFINITY
-    pcs -f hw_cfg constraint location sspl_master_hw prefers $host2=INFINITY
+        op stop timeout=30s interval=0s 2> "${TMP_LOG}" || handle_error
+    pcs -f hw_cfg resource update sspl_master_hw meta migration-threshold=1 failure-timeout=40s 2> "${TMP_LOG}" || handle_error
+    pcs -f hw_cfg constraint colocation add sspl_master_hw with sspl-master INFINITY with-rsc-role=Master 2> "${TMP_LOG}" || handle_error
+    pcs -f hw_cfg constraint location sspl_master_hw prefers "${HOST1}"=INFINITY 2> "${TMP_LOG}" || handle_error
+    pcs -f hw_cfg constraint location sspl_master_hw prefers "${HOST2}"=INFINITY 2> "${TMP_LOG}" || handle_error
     pcs cluster cib-push hw_cfg
 
     pcs cluster cib iem_cfg
@@ -55,30 +105,65 @@ init() {
         path='node_iem_s3' filename='node_iem_s3' service="slapd" \
         op start timeout=30s interval=0s \
         op monitor timeout=30s interval=30s \
-        op stop timeout=30s interval=0s
-    pcs -f iem_cfg resource clone node_iem_s3 clone-max=2 clone-node-max=1
-    pcs -f iem_cfg constraint location node_iem_s3-clone prefers ${host1}=INFINITY
-    pcs -f iem_cfg constraint location node_iem_s3-clone prefers ${host2}=INFINITY
-    pcs -f iem_cfg constraint order node_iem_s3-clone then ldap-clone
+        op stop timeout=30s interval=0s 2> "${TMP_LOG}" || handle_error
+    pcs -f iem_cfg resource clone node_iem_s3 clone-max=2 clone-node-max=1 2> "${TMP_LOG}" || handle_error
+    pcs -f iem_cfg constraint location node_iem_s3-clone prefers "${HOST1}"=INFINITY 2> "${TMP_LOG}" || handle_error
+    pcs -f iem_cfg constraint location node_iem_s3-clone prefers "${HOST2}"=INFINITY 2> "${TMP_LOG}" || handle_error
+    pcs -f iem_cfg constraint order node_iem_s3-clone then ldap-clone 2> "${TMP_LOG}" || handle_error
     pcs cluster cib-push iem_cfg
+
+    verify_resources
 }
 
 cleanup() {
+    RESOURCE_LIST=$(pcs resource)
     echo "Delete resources"
-    resources=(
-        io_path_health-c1
-        io_path_health-c2
-        mgmt_path_health-c1
-        node_iem_s3
-        sspl_master_hw
-    )
-    for r in ${resources[@]}; do
-        pcs resource delete $r &
+    for resource in ${resources[@]}; do
+        echo $RESOURCE_LIST | grep -q $resource && pcs resource delete $resource || {
+            echo "$resource resource already deleted"
+        } &
     done
     wait
 }
 
-ACTION=$1
-ARGS=$2
+usage() {
+    cat <<EOF
+Usage: $PROG <Action> [node_schama]
 
-$ACTION $ARGS
+Configures HW/IEM HA by preparing the configuration files and
+adding resources into the Pacemaker.
+
+Caveats:
+
+* The script expects Pacemaker to be started and have no resources configured.
+  Check with 'pcs status'.
+
+* hw_comp_ra, iem_comp_ra resource should be available.
+
+Mandatery Parameters:
+Action:
+    init: To configure all hw/iem resources
+    cleanup: To delete hw/iem resources
+node_schama:
+    It need prameter.yaml file
+
+prameter.yaml
+----------------------------
+HOST1: <HOST1>
+HOST2: <HOST2>
+
+EOF
+}
+
+ACTION=$1
+PARAM=$2
+mkdir -p ${LOG_PATH}
+
+if [ -f $PARAM ]; then
+    HOST1=$(cat $PARAM | grep HOST1 | awk '{print $2}')
+    HOST2=$(cat $PARAM | grep HOST2 | awk '{print $2}')
+else
+    usage
+fi
+
+$ACTION
diff --git a/conf/script/build-ees-ha-csm b/conf/script/build-ees-ha-csm
--- a/conf/script/build-ees-ha-csm
+++ b/conf/script/build-ees-ha-csm
@@ -64,6 +64,12 @@ lnode=pod-c1
 rnode=pod-c2
 update=false
 cib_file=/var/lib/hare/cib_cortx_cluster.xml
+ha_lib=/var/lib/hare/
+LOG_DIR="/var/log/seagate/cortx/ha"
+TMP_LOG="/tmp/ha.log"
+LOG="${LOG_DIR}/${0##*/}.log"
+
+mkdir -p "${LOG_DIR}"
 
 while true; do
     case "$1" in
@@ -97,6 +103,51 @@ fi
 [[ $vip ]] || {
     usage >&2
     exit 1
+}
+
+resources=(
+    kibana-vip
+    kibana
+    csm-agent
+)
+
+dependency_resource=(
+    consul-c1
+    consul-c2
+    els-search-clone
+    rabbitmq-clone
+)
+
+handle_error() {
+    MSG=$(cat ${TMP_LOG})
+    echo "$(date '+%Y-%m-%d %H:%M:%S'): ${MSG}" >> ${LOG}
+    echo ${MSG} | grep -q "already" || {
+        echo "ERROR: ${MSG}"
+        exit 1
+    }
+}
+
+verify_resources() {
+    RESOURCE_LIST=$(pcs resource)
+    for resource in ${resources[@]}; do
+        echo ${RESOURCE_LIST} | grep -q ${resource} || {
+            echo "Error: ${resource} resource is missing. Check log at ${LOG}"
+            exit 1
+        }
+    done
+    echo "CSM Managment resource configured successfully."
+    exit 0
+}
+
+verify_dependency_resources() {
+    RESOURCE_LIST=$(pcs resource)
+    for resource in ${dependency_resource[@]}; do
+        echo ${RESOURCE_LIST} | grep -q ${resource} || {
+            echo "Error: ${resource} resource is missing. Log at ${LOG}"
+            exit 1
+        }
+    done
+    echo "Dependency resource check passed..."
 }
 
 die() {
@@ -146,40 +197,41 @@ kibana_rsc_add() {
         ip=$vip cidr_netmask=24 nic=$iface iflabel=v1 \
         op start   interval=0s timeout=60s \
         op monitor interval=5s timeout=20s \
-        op stop    interval=0s timeout=60s
-    sudo pcs -f $cib_file resource create kibana systemd:kibana op monitor interval=30s
+        op stop    interval=0s timeout=60s 2> "${TMP_LOG}" || handle_error
+    sudo pcs -f $cib_file resource create kibana systemd:kibana op monitor interval=30s 2> "${TMP_LOG}" || handle_error
 }
 
 csm_rsc_add() {
     echo 'Adding csm resources and constraints...'
 
     sudo pcs -f $cib_file resource create csm-agent systemd:csm_agent op \
-        monitor interval=30s
+        monitor interval=30s 2> "${TMP_LOG}" || handle_error
     sudo pcs -f $cib_file resource create csm-web systemd:csm_web op \
-        monitor interval=30s
+        monitor interval=30s 2> "${TMP_LOG}" || handle_error
 
     sudo pcs -f $cib_file resource group add \
-        csm-kibana kibana-vip kibana csm-web csm-agent
+        csm-kibana kibana-vip kibana csm-web csm-agent 2> "${TMP_LOG}" || handle_error
 
-    sudo pcs -f $cib_file constraint order consul-c1 then csm-web
-    sudo pcs -f $cib_file constraint order consul-c2 then csm-web
-    sudo pcs -f $cib_file constraint order els-search-clone then csm-kibana
+    sudo pcs -f $cib_file constraint order consul-c1 then csm-web 2> "${TMP_LOG}" || handle_error
+    sudo pcs -f $cib_file constraint order consul-c2 then csm-web 2> "${TMP_LOG}" || handle_error
+    sudo pcs -f $cib_file constraint order els-search-clone then csm-kibana 2> "${TMP_LOG}" || handle_error
 
-    sudo pcs -f $cib_file constraint location csm-kibana prefers $lnode
+    sudo pcs -f $cib_file constraint location csm-kibana prefers $lnode 2> "${TMP_LOG}" || handle_error
 
     sudo pcs -f $cib_file constraint location csm-kibana rule score=-INFINITY \
-        '#uname' eq $lnode and consul-c1-running eq 0
+        '#uname' eq $lnode and consul-c1-running eq 0 2> "${TMP_LOG}" || handle_error
     sudo pcs -f $cib_file constraint location csm-kibana rule score=-INFINITY \
-        '#uname' eq $rnode and consul-c2-running eq 0
+        '#uname' eq $rnode and consul-c2-running eq 0 2> "${TMP_LOG}" || handle_error
 
     sudo pcs -f $cib_file constraint colocation add csm-kibana with els-search-clone \
-        score=INFINITY
+        score=INFINITY 2> "${TMP_LOG}" || handle_error
     sudo pcs -f $cib_file constraint colocation add csm-kibana with rabbitmq-clone \
-        score=INFINITY
+        score=INFINITY 2> "${TMP_LOG}" || handle_error
 }
 
 cib_init() {
-   sudo pcs cluster cib $cib_file
+    mkdir -p ${ha_lib}
+    sudo pcs cluster cib $cib_file
 }
 
 cib_commit() {
@@ -190,8 +242,10 @@ cib_commit() {
 ha_ops=(
     precheck
     systemd_disable
+    verify_dependency_resources
     kibana_rsc_add
     csm_rsc_add
+    verify_resources
 )
 
 # Maps ha operation from the ha_ops table to its respective type.
@@ -201,8 +255,10 @@ ha_ops=(
 declare -A ha_ops_type=(
     [precheck]='bootstrap'
     [systemd_disable]='bootstrap'
+    [verify_dependency_resources]='bootstrap'
     [kibana_rsc_add]='update'
     [csm_rsc_add]='update'
+    [verify_resources]='update'
 )
 
 for op in ${ha_ops[@]}; do
diff --git a/conf/script/build-ees-ha-sspl b/conf/script/build-ees-ha-sspl
--- a/conf/script/build-ees-ha-sspl
+++ b/conf/script/build-ees-ha-sspl
@@ -53,6 +53,12 @@ lnode=pod-c1
 rnode=pod-c2
 update=false
 cib_file=/var/lib/hare/cib_cortx_cluster.xml
+ha_lib=/var/lib/hare/
+LOG_DIR="/var/log/seagate/cortx/ha"
+TMP_LOG="/tmp/ha.log"
+LOG="${LOG_DIR}/${0##*/}.log"
+
+mkdir -p "${LOG_DIR}"
 
 while true; do
     case "$1" in
@@ -81,6 +87,47 @@ fi
 [[ $lnode ]] && [[ $rnode ]] || {
     usage >&2
     exit 1
+}
+
+resources=(
+    sspl-master
+)
+
+dependency_resource=(
+    consul-c1
+    consul-c2
+)
+
+handle_error() {
+    MSG=$(cat ${TMP_LOG})
+    echo "$(date '+%Y-%m-%d %H:%M:%S'): ${MSG}" >> ${LOG}
+    echo ${MSG} | grep -q "already" || {
+        echo "ERROR: ${MSG}"
+        exit 1
+    }
+}
+
+verify_resources() {
+    RESOURCE_LIST=$(pcs resource)
+    for resource in ${resources[@]}; do
+        echo ${RESOURCE_LIST} | grep -q ${resource} || {
+            echo "Error: ${resource} resource is missing. Check log at ${LOG}"
+            exit 1
+        }
+    done
+    echo "SSPL resource configured successfully."
+    exit 0
+}
+
+verify_dependency_resources() {
+    RESOURCE_LIST=$(pcs resource)
+    for resource in ${dependency_resource[@]}; do
+        echo ${RESOURCE_LIST} | grep -q ${resource} || {
+            echo "Error: ${resource} resource is missing. Log at ${LOG}"
+            exit 1
+        }
+    done
+    echo "Dependency resource check passed..."
 }
 
 die() {
@@ -116,13 +163,13 @@ sspl_rsc_add() {
     echo 'Adding sspl resource and constraints...'
 
     sudo pcs -f $cib_file resource create sspl ocf:cortx:sspl \
-        master meta migration-threshold=10 failure-timeout=10s is-managed=true
-    sudo pcs -f $cib_file constraint order consul-c1 then sspl-master kind=Optional
-    sudo pcs -f $cib_file constraint order consul-c2 then sspl-master kind=Optional
+        master meta migration-threshold=10 failure-timeout=10s is-managed=true 2> "${TMP_LOG}" || handle_error
+    sudo pcs -f $cib_file constraint order consul-c1 then sspl-master kind=Optional 2> "${TMP_LOG}" || handle_error
+    sudo pcs -f $cib_file constraint order consul-c2 then sspl-master kind=Optional 2> "${TMP_LOG}" || handle_error
     sudo pcs -f $cib_file constraint order consul-c1 then promote sspl-master \
-         kind=Optional
+         kind=Optional 2> "${TMP_LOG}" || handle_error
     sudo pcs -f $cib_file constraint order consul-c2 then promote sspl-master \
-         kind=Optional
+         kind=Optional 2> "${TMP_LOG}" || handle_error
 
 # failure-timeout "is not guaranteed to be checked more frequently than"
 # cluster-recheck-interval, see more at
@@ -133,11 +180,16 @@ sspl_rsc_add() {
 consul_config() {
     echo 'Copying Consul configuration files...'
 
-    sudo cp /opt/seagate/cortx/sspl/bin/consul_config.json \
-           $hare_dir/consul-server-c1-conf/
+    [ -f /opt/seagate/cortx/sspl/bin/consul_config.json ] || {
+        sudo cp /opt/seagate/cortx/sspl/bin/consul_config.json \
+            $hare_dir/consul-server-c1-conf/
+    }
+
     cmd="
-    cp /opt/seagate/cortx/sspl/bin/consul_config.json \
-       $hare_dir/consul-server-c2-conf/"
+    [ -f /opt/seagate/cortx/sspl/bin/consul_config.json ] ||
+        cp /opt/seagate/cortx/sspl/bin/consul_config.json \
+            $hare_dir/consul-server-c2-conf/
+    "
     ssh $rnode $cmd
 
     echo 'Reloading Consul...'
@@ -145,7 +197,8 @@ consul_config() {
 }
 
 cib_init() {
-   sudo pcs cluster cib $cib_file
+    mkdir -p ${ha_lib}
+    sudo pcs cluster cib $cib_file
 }
 
 cib_commit() {
@@ -156,8 +209,10 @@ cib_commit() {
 ha_ops=(
     precheck
     systemd_disable
+    verify_dependency_resources
     sspl_rsc_add
     consul_config
+    verify_resources
 )
 
 # Maps ha operation from the ha_ops table to its respective type.
@@ -167,8 +222,10 @@ ha_ops=(
 declare -A ha_ops_type=(
     [precheck]='bootstrap'
     [systemd_disable]='bootstrap'
+    [verify_dependency_resources]='bootstrap'
     [sspl_rsc_add]='update'
     [consul_config]='bootstrap'
+    [verify_resources]='update'
 )
 
 for op in ${ha_ops[@]}; do
diff --git a/conf/script/build-ees-ha-uds b/conf/script/build-ees-ha-uds
--- a/conf/script/build-ees-ha-uds
+++ b/conf/script/build-ees-ha-uds
@@ -33,6 +33,10 @@ eval set -- "$TEMP"
 
 update=false
 cib_file=/var/lib/hare/cib_cortx_cluster.xml
+ha_lib=/var/lib/hare/
+LOG_DIR="/var/log/seagate/cortx/ha"
+TMP_LOG="/tmp/ha.log"
+LOG="${LOG_DIR}/${0##*/}.log"
 
 while true; do
     case "${1:-default}" in
@@ -44,6 +48,46 @@ while true; do
     esac
 done
 
+resources=(
+    uds
+)
+
+dependency_resource=(
+    csm-agent
+)
+
+handle_error() {
+    MSG=$(cat ${TMP_LOG})
+    echo "$(date '+%Y-%m-%d %H:%M:%S'): ${MSG}" >> ${LOG}
+    echo ${MSG} | grep -q "already" || {
+        echo "ERROR: ${MSG}"
+        exit 1
+    }
+}
+
+verify_resources() {
+    RESOURCE_LIST=$(pcs resource)
+    for resource in ${resources[@]}; do
+        echo ${RESOURCE_LIST} | grep -q ${resource} || {
+            echo "Error: ${resource} resource is missing. Check log at ${LOG}"
+            exit 1
+        }
+    done
+    echo "UDS resource configured successfully."
+    exit 0
+}
+
+verify_dependency_resources() {
+    RESOURCE_LIST=$(pcs resource)
+    for resource in ${dependency_resource[@]}; do
+        echo ${RESOURCE_LIST} | grep -q ${resource} || {
+            echo "Error: ${resource} resource is missing. Log at ${LOG}"
+            exit 1
+        }
+    done
+    echo "Dependency resource check passed..."
+}
+
 precheck() {
     # Abort (set -e) if `csm-agent` resource does not exist.
     sudo pcs resource show csm-agent >/dev/null
@@ -51,15 +95,16 @@ precheck() {
 
 uds_rsc_add() {
     echo 'Adding UDS resource and constraints...'
-    sudo pcs -f $cib_file resource create uds systemd:uds op monitor interval=30s
-    sudo pcs -f $cib_file constraint colocation add uds with csm-agent score=INFINITY
+    sudo pcs -f $cib_file resource create uds systemd:uds op monitor interval=30s 2> "${TMP_LOG}" || handle_error
+    sudo pcs -f $cib_file constraint colocation add uds with csm-agent score=INFINITY 2> "${TMP_LOG}" || handle_error
 
     # According to EOS-9258, there is a bug which requires UDS to be started after csm_agent
-    sudo pcs -f $cib_file constraint order csm-agent then uds
+    sudo pcs -f $cib_file constraint order csm-agent then uds 2> "${TMP_LOG}" || handle_error
 }
 
 cib_init() {
-   sudo pcs cluster cib $cib_file
+    mkdir -p ${ha_lib}
+    sudo pcs cluster cib $cib_file
 }
 
 cib_commit() {
@@ -69,7 +114,9 @@ cib_commit() {
 # HA operations table.
 ha_ops=(
     precheck
+    verify_dependency_resources
     uds_rsc_add
+    verify_resources
 )
 
 # Maps ha operation from the ha_ops table to its respective type.
@@ -78,7 +125,9 @@ ha_ops=(
 # update:      executes during clean install and software update
 declare -A ha_ops_type=(
     [precheck]='bootstrap'
+    [verify_dependency_resources]='bootstrap'
     [uds_rsc_add]='update'
+    [verify_resources]='update'
 )
 
 for op in ${ha_ops[@]}; do
