- Configure alert in ha resource setup - Add logic for alert remove
Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

diff --git a/conf/script/build-cortx-ha b/conf/script/build-cortx-ha
--- a/conf/script/build-cortx-ha
+++ b/conf/script/build-cortx-ha
@@ -19,8 +19,21 @@
 set -eu -o pipefail
 
 HA_PATH="<HA_PATH>"
+HA_LOG="/var/log/seagate/cortx/ha"
+
+configure_alert() {
+    pcs alert show | grep ha_iem_event || pcs alert create id=ha_iem_event \
+        description="Log events for iem." path=${HA_PATH}/bin/pcs_iem
+    pcs alert show | grep ha_iem_recipient || pcs alert recipient add ha_iem_event \
+        id=ha_iem_recipient value=${HA_LOG}/
+    pcs alert show | grep ha_iem_event && pcs alert show | grep ha_iem_recipient && \
+        echo "HA IEM configured Successfully" || { echo "Fail to configure iem"; exit 1; }
+}
 
 init() {
+    # Configure alert
+    configure_alert
+
     # Get node name
     node_list=$(salt-call --local pillar.get cluster:node_list --output=json)
     host1=$(echo $node_list | jq '.["local"][0]' | sed s/\"//g)
@@ -77,6 +90,9 @@ init() {
 }
 
 cleanup() {
+    echo "Delete alert"
+    pcs alert show | grep ha_iem_event && pcs alert remove ha_iem_event
+
     echo "Delete resources"
     resources=(
         io_path_health-c1
