Generate IEM for ha event (#217)
* Generate IEM for ha event

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

* Added Alert Generator for ha IEM.
Provided schema for IEM.

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

* Make host dynamic

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

* Add check for iem alert setup

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

* Remove unwanted code

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

* Improved IEM event

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

* Codacy fix

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

* Added entry point for pcs_iem trigger point

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

* ha_setup update pcs_iem

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

* - Configure alert in ha resource setup
- Add logic for alert remove

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

* Remove unused import pathlib

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

* changed UUID to HOST

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

* Modified code and iem event handler.

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

* Remove json unused import

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

Co-authored-by: ajaysrivas <66410865+ajaysrivas@users.noreply.github.com>

diff --git a/conf/script/ha_setup b/conf/script/ha_setup
--- a/conf/script/ha_setup
+++ b/conf/script/ha_setup
@@ -35,8 +35,6 @@ exec &> >(stdbuf -oL gawk '{ print strftime("%Y-%m-%d %H:%M:%S"), $0 }')
 
 post_install() {
     echo "post_install"
-    # Add permisson to hacluster
-    add_permission
 
     if [ ! -d "${LOGROTATE_CONF_DIR}" ]; then
         mkdir -p ${LOGROTATE_CONF_DIR}
@@ -65,6 +63,9 @@ init() {
     echo "init"
     # Add consul watcher
     consul_watcher_failback
+
+    # Add permisson to hacluster
+    add_permission
 }
 
 test() {
@@ -200,6 +201,22 @@ config_decision_maker() {
 
     cp -rf /tmp/decision_monitor_conf.json /etc/cortx/ha/decision_monitor_conf.json
     rm -rf /tmp/decision_monitor_conf.json
+
+    # Configure ha_iem event get info from Decision maker
+    config_ha_iem_event ${host1} ${uuid1} ${host2} ${uuid2}
+}
+
+config_ha_iem_event() {
+    echo "Configure IEM for ha event"
+    cp -rf ${SOURCE_HA_CONF}/iem_ha.json ${HA_CONF}
+
+    # Configure alert for HA IEM
+    setfacl -R -m u:hacluster:rwx ${HA_LOG} || {
+        echo "Failed to add permission for hacluster log"; exit 1;
+    }
+    setfacl -R -m g:haclient:rwx ${HA_LOG} || {
+        echo "Failed to add permission for haclient log"; exit 1;
+    }
 }
 
 ACTION=$1
